sonar.projectKey=todo-project
sonar.projectName=Todo Project
sonar.projectVersion=1.0

sonar.sources=backend,frontend/src

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/__pycache__/**,**/venv/**,**/.venv/**,**/.terraform/**,**/coverage/**

sonar.python.version=3.11
