[docker_agent]
docker-agent ansible_host=10.0.1.64 ansible_user=ubuntu

[deploy_agent]
deploy-agent ansible_host=10.0.1.42 ansible_user=ubuntu

[k8s_control]
k8s-control ansible_host=10.0.1.202 ansible_user=ubuntu

[k8s_worker]
k8s-worker ansible_host=10.0.1.11 ansible_user=ubuntu

[k8s:children]
k8s_control
k8s_worker

[jenkins_agents:children]
docker_agent
deploy_agent

[servers:children]
docker_agent
deploy_agent
k8s_control
k8s_worker

[servers:vars]
ansible_ssh_private_key_file=/home/ubuntu/todo-infra-kp.pem