---
- name: Common setup for all servers
  hosts: servers
  become: true
  roles:
    - serversetup

- name: Configure Docker build agent
  hosts: docker_agent
  become: true
  roles:
    - docker_agent

- name: Configure deploy agent
  hosts: deploy_agent
  become: true
  roles:
    - deploy_agent

- name: Prepare Kubernetes nodes
  hosts: k8s
  become: true
  roles:
    - k8s_common

- name: Configure Kubernetes control plane
  hosts: k8s_control
  become: true
  roles:
    - k8s_control

- name: Join Kubernetes worker node
  hosts: k8s_worker
  become: true
  roles:
    - k8s_worker